[versions]
hec-monolith = "5.3.5"
guava = "11.0.2"
commons-io = "2.1"
xstream = "1.4.3"
javatuples = "1.2"
java-object-diff = "0.95"
kryo = "2.24.0"
jep = "3.8.2"
libtensorflow = "1.14.0"
testng = "6.3"
junit_5 = "5.10.2"
antlr = "3.5.2"
tattletale = "1.2.0.Beta2"
jarhdf5 = "2.11.0"
linearsolver = "2013-01-10"
gurobi = "5.0"
jcbc = "2021-12-27"
lpsolve55j = "2009.08.23"
xaoptimizer = "2016.11.04"
calsurrogate = "2023.12.25"
runlibs = "0.1.0"
callitetest = "0.2.4"
system-summary-report-tool = "1.0.3"
javaHeclib = "7-IU-4-win-x86_64"
graalvm = "24.2.1"

[libraries]
hec-monolith = { module = "mil.army.usace.hec:hec-monolith", version.ref = "hec-monolith" }
hec-monolith-bom = { module = "mil.army.usace.hec:hec-monolith-bom", version.ref = "hec-monolith" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
xstream = { module = "com.thoughtworks.xstream:xstream", version.ref = "xstream" }
javatuples = { module = "org.javatuples:javatuples", version.ref = "javatuples" }
java-object-diff = { module = "de.danielbechler:java-object-diff", version.ref = "java-object-diff" }
kryo = { module = "com.esotericsoftware.kryo:kryo", version.ref = "kryo" }
jep = { module = "black.ninia:jep", version.ref = "jep" }
libtensorflow = { module = "org.tensorflow:libtensorflow", version.ref = "libtensorflow" }
testng = { module = "org.testng:testng", version.ref = "testng" }
junit-5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit_5" }
junit-5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit_5" }
junit-5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit_5" }
antlr = { module = "org.antlr:antlr", version.ref = "antlr" }
tattletale = { module = "org.jboss.tattletale:tattletale", version.ref = "tattletale"}
jarhdf5 = { module = "ncsa.hdf.hdf5lib:jarhdf5", version.ref = "jarhdf5" }
linearsolver = { module = "com.google.ortools:linearsolver", version.ref = "linearsolver" }
gurobi = { module = "gurobi:gurobi", version.ref = "gurobi" }
jcbc = { module = "gov.ca.dwr:jcbc", version.ref = "jcbc" }
lpsolve55j = { module = "lpsolve:lpsolve55j", version.ref = "lpsolve55j" }
xaoptimizer = { module = "com.sunsetsoft.xa:xaoptimizer", version.ref = "xaoptimizer" }
calsurrogate = { module = "gov.ca.dwr.deltamodeling:calsurrogate", version.ref = "calsurrogate" }
system-summary-report-tool = { module = "gov.ca.dwr:system-summary-report-tool", version.ref = "system-summary-report-tool"}
run-libs = { group = "gov.ca.dwr", name = "run-libs", version.ref = "runlibs" }
cal-lite-test = { group = "gov.ca.dwr", name = "cal_lite_test_01", version.ref = "callitetest" }
javaHeclib = { module = "mil.army.usace.hec:javaHeclib", version.ref = "javaHeclib" }
graalvm-polyglot = { module = "org.graalvm.polyglot:polyglot", version.ref = "graalvm" }
graalvm-python = { module = "org.graalvm.polyglot:python", version.ref = "graalvm" }
graalvm-embedding = { module = "org.graalvm.python:python-embedding", version.ref = "graalvm" }

[bundles]
junit5 = [ "junit-5-engine", "junit-5-api", "junit-5-params" ]
