name: Comparison Tests - Manual
#This workflow is triggered manually to run comparison tests, it will NOT run automatically on a push or pull request.

on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:

  comparison-tests:
    runs-on:
      - self-hosted
      - azure
      - comparison-runner
    env:
      WRIMS_AZURE_SAS: ${{ secrets.WRIMS_AZURE_SAS }}

    steps:
      - uses: actions/checkout@v2

      - name: Check bash
        run: bash --version
        shell: bash

      - name: Verify token access to wrims-engine-dependencies
        shell: bash
        run: |
          curl --fail -i -u "dwr-wrims-build:${{ secrets.WRIMS_ENGINE_DEPENDENCIES_TOKEN }}" \
            https://maven.pkg.github.com/CentralValleyModeling/wrims-engine-dependencies/com.google.ortools/linearsolver/2013-01-10/linearsolver-2013-01-10.jar

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Clean & Run Azure Compute Tests
        run: |
          ./gradlew clean -PcvmUserId="dwr-wrims-build" -PcvmPassword="${{ secrets.WRIMS_ENGINE_DEPENDENCIES_TOKEN }}"
          ./gradlew runAzureCucumberTests -PcvmUserId="dwr-wrims-build" -PcvmPassword="${{ secrets.WRIMS_ENGINE_DEPENDENCIES_TOKEN }}"          

      - name: Upload Comparison Report
        if: always()
        uses: actions/upload-artifact@v4.0.0
        with:
          name: comparison-report
          path: |
            ./wrims-comparison-test/build/testProjects/**/*.pdf
            ./wrims-comparison-test/build/testProjects/**/*VALIDATION*