name: SonarCloud Scan
on:
  workflow_run:
    workflows: ["Java CI"]
    type: [completed]
  push:
    branches:
      - main
env:
  WRIMS_ENGINE_DEPENDENCIES: ${{ secrets.WRIMS_ENGINE_DEPENDENCIES_TOKEN }}


jobs:
  Sonar:
    name: SonarCloud Scanner
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'push'
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4.2.2
        env:
          REPO: ${{ github.event.workflow_run.head_repository.full_name }}
          REF: ${{ github.event.workflow_run.head_branch }}
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.REF }}
          fetch-depth:
            0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 21
          distribution: temurin
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.1
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: |
          ./gradlew clean -PcvmUserId="dwr-wrims-build" -PcvmPassword="$WRIMS_ENGINE_DEPENDENCIES"
          ./gradlew build -PcvmUserId="dwr-wrims-build" -PcvmPassword="$WRIMS_ENGINE_DEPENDENCIES"
      - name: Analyze
        id: sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REVISION: ${{ github.event.workflow_run.head_sha }}
          REQUEST_NUM: ${{ github.event.workflow_run.pull_requests[0].number }}
          REQUEST_BRANCH: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          BASE_BRANCH: ${{ github.event.workflow_run.pull_requests[0].base.ref }}
        run: |
          ./gradlew sonar \
                  -PcvmUserId="dwr-wrims-build" \
                  -PcvmPassword="$WRIMS_ENGINE_DEPENDENCIES" \
                  --info \
                  -Dsonar.scm.revision=$REVISION \
                  -Dsonar.pullrequest.key=$REQUEST_NUM \
                  -Dsonar.pullrequest.branch=$REQUEST_BRANCH \
                  -Dsonar.pullrequest.base=$BASE_BRANCH
      - name: Upload Failure Report
        if: failure()
        uses: actions/upload-artifact@v5.0.0
        with:
          name: sonar-failure-report
          path: /home/runner/work/wrims-engine/wrims-engine/build/reports/problems/problems-report.html
          retention-days: 7